### ISSUE TITLE
Update dependency on analyzer 1.0.0

### ISSUE THREAD

**Issue by kaciula** [marcinsiedlik/auto_localized#10]
Can you please update the dependencies so I can use the latest json_serializable, freezed packages?

Thanks.

Because no versions of auto_localized_generator match >1.0.1 <2.0.0 and auto_localized_generator 1.0.1 depends on analyzer ^1.0.0, auto_localized_generator ^1.0.1 requires analyzer ^1.0.0.

**Comment by marcinsiedlik** [comment]
Hi, right now I'm low on free time but i will try to do this asap
