### ISSUE TITLE
Update to analyzer 4.6.0

### ISSUE THREAD

**Issue by kaciula** [marcinsiedlik/auto_localized#15]
Please update the package to depend on the new analyzer 4.6.0 

Flutter 3.3 forces me to use this new version for build_runner but I cannot because of auto_localized dependency on  analyzed >1.3.0 <2.0.0

**Comment by marcinsiedlik** [comment]
Hi, the new version of the package with updated dependencies was published. If you have any questions feel free to leave a comment
