### ISSUE TITLE
Update dependency on source_gen

### ISSUE THREAD

**Issue by kaciula** [marcinsiedlik/auto_localized#6]
Hi. Could you please update the dependency on source_gen?

`Because hive_generator >=1.0.1 depends on source_gen ^1.0.0 and auto_localized_generator >=1.0.0 depends on source_gen ^0.9.10+3, hive_generator >=1.0.1 is incompatible with auto_localized_generator >=1.0.0.`

**Comment by marcinsiedlik** [comment]
Hi, of course I will release an update asap

**Comment by marcinsiedlik** [comment]
New version has been released, if you have any questions or problems feel free to reopen
