### ISSUE TITLE
Getting translation by string key

### ISSUE THREAD

**Issue by cirnok** [marcinsiedlik/auto_localized#8]
Nice package for translations, but doesn't allow getting translation by string key.
Example:
```dart
Strings.getByKey('Authentication:InvalidCredentials').get();
```
This is useful if the data comes from outside the client, for example, from a server. Otherwise, you have to create unnecessary wrappers that make your code worse.
Example:
```dart
static String _localizeDomainFailure(DomainFailure failure) {
  switch (failure.code) {
    case "Authentication:InvalidCredentials":
      return Strings.authenticationInvalidCredentials.get();
    case "Refresh:InvalidRefreshToken":
     return Strings.refreshInvalidRefreshToken.get();
    case "Registration:UserAlreadyExists":
     return Strings.registrationUserAlreadyExists.get();
  }

  return Strings.unknownFailure.get();
}
```

**Comment by marcinsiedlik** [comment]
Hi, this wasn't implemented on purpose, to keep library free of possible runtime failures. 
But now, it can be added as optional feature

**Comment by marcinsiedlik** [comment]
The feature is merged and will become available in the next release.
Closing this issue, in case of any questions fell free to comment
