### ISSUE TITLE
Nested json objects for easier translation

### ISSUE THREAD

**Issue by kaciula** [marcinsiedlik/auto_localized#9]
Thanks for the great package. It works beautifully.

I wish there is the possibility of having nested json objects so that I can partition the strings based on the screen they appear on. This is helpful because the json file is then imported in an app like Babel and someone non-technical can go and easily change the translations of a string from a particular screen. Right now, all the texts are in one big list.

What do you think? Is this easy to implement? The way I see it, the plugin should traverse the json and include all the leaf nodes.

**Comment by marcinsiedlik** [comment]
Hi, sorry to keep you waiting. This is a great idea and can give real benefits while maintaining translations. I think that the best way to add that functionally without introducing complexity is to implement support for multiple files per locale. Then the user could split strings into as many files and directories as they like (per screen, category, etc)

For example:
```bash
lang
├── en
│   ├── about.yml
│   ├── main.yml
│   ├── other.yml
│   └── settings.yml
└── pl
    ├── about.yml
    ├── main.yml
    ├── other.yml
    └── settings.yml
```

**Comment by kaciula** [comment]
Sounds like an even better idea.

**Comment by marcinsiedlik** [comment]
The feature is implemented and the new version is released, closing
